config/routes.rb
Rails.application.routes.draw do
  resources :transactions, except: [:show]
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :groups, except: [:destroy,:edit]
  resources :user, only: [:show]
  root "user#show"
  get '/etransactions', to: 'transactions#etransaction'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  validates :title, presence: true
  validates :icon, presence: true

  belongs_to :user
  has_many :transactions, dependent: :destroy

  mount_uploader :icon, ImageUploader
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  validates :title, length: { minimum: 10 }
  validates :amount, presence: true

  belongs_to :user
  belongs_to :group, optional: true

  scope :grouped, -> { where.not(group: [nil]).order('created_at DESC') }
  scope :non_grouped, -> { where(group: [nil]).order('created_at DESC') }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :transactions
  has_many :groups
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.includes(:user, :transactions).where(user_id: current_user)
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])
    @gtransactions = @group.transactions.includes(:user).where(user_id: current_user)
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.build(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_path, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:title, :icon, :user_id)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[show edit update destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = @transactions = Transaction.includes(:group).where(user_id: current_user).grouped
    @transaction_sum = Transaction.where(user_id: current_user).grouped.sum(:amount)
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit; end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = current_user.transactions.build(transaction_params)

    respond_to do |format|
      if @transaction.save
        if @transaction.group_id.nil?
          format.html do
            redirect_to '/etransactions',
                        notice: 'Transaction was successfully created.'
          end
        else
          format.html do
            redirect_to '/transactions',
                        notice: 'Transaction was successfully created.'
          end
        end
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        if @transaction.group_id.nil?
          format.html do
            redirect_to '/etransactions',
                        notice: 'Transaction was successfully created.'
          end
        else
          format.html do
            redirect_to '/transactions',
                        notice: 'Transaction was successfully created.'
          end
        end
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      if @transaction.group_id.nil?
        format.html do
          redirect_to etransactions_url,
                      notice: 'Transaction was successfully destroyed.'
        end
      else
        format.html do
          redirect_to transactions_url,
                      notice: 'Transaction was successfully destroyed.'
        end

      end
    end
  end

  def etransaction
    @etransactions = Transaction.where(user_id: current_user).non_grouped
    @etransaction_sum = Transaction.where(user_id: current_user).non_grouped.sum(:amount)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def transaction_params
    params.require(:transaction).permit(:title, :amount, :user_id, :group_id)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def showbtns
    return unless user_signed_in?

    link_to 'log out', destroy_user_session_path, method: :delete,
                                                  class: 'mr-3 bg-danger
                                                      text-white px-2 py-1
                                                      radius w-100 d-md-inline
                                                      d-block'
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class:"w-100 mb-2" %>
  </div>

  <div class="field">
    <%= form.label :icon %> <br>
    <%= form.file_field :icon ,class:"mb-2"%>
  </div>


  <div class="actions">
    <%= form.submit "Submit",class:"btn btn-warning btn-block rounded-0 py-2 mb-3" %>
  </div>

<% end %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>


<h4 class="text-center">All Groups</h4>

<div class="container2 px-0 py-2 px-1 overflow-auto">

    <% @groups.each do |group| %>


    <div class="card mb-1">
      <div class="card-body text-primary d-flex justify-content-between">
        <div class="d-flex align-items-center">
          <img src="<%=group.icon%>" class="size mr-2 rounded-circle"/>
          <h5><%= group.title.capitalize %></h5>
          </div>
      <div class="btns">
      <%= link_to '<button class="btn-primary border-0"><i class="fas fa-chalkboard fa-1x text-white"></i></button>'.html_safe, group %>
      </div>
      </div>
    </div>
    <% end %>

<br>
</div>

<%= link_to 'New Group', new_group_path, class:"bg-success text-white w-100 d-block mt-4 text-center py-2 mb-3" %>
<%=link_to ' <i class="fas fa-home"></i> Home'.html_safe, user_path(current_user), class:"mr-3 bg-dark text-white text-center px-2 py-1 radius w-100"%>

app/views/groups/new.html.erb
<h4 class="text-center mt-2">Create New Group</h4>

<%= render 'form', group: @group %>

<%= link_to ' <i class="fas fa-arrow-left"></i> Back'.html_safe, groups_path,class:"text-white bg-dark px-2 py-1" %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<div class="d-flex align-items-center justify-content-center">
  <img src="<%=@group.icon%>" class="size mr-2 rounded-circle"/>
  <h5><%= @group.title.capitalize %></h5>
</div>

  <div class="container2 px-0 py-2 px-1 overflow-auto my-3">

  <% @gtransactions.each do |gtransaction| %>
  <div class="card mb-3">
    <div class="card-body text-primary">
      <div class="d-flex justify-content-between">
        <h5><%= gtransaction.title.capitalize%></h5>
        <h5><%= number_to_currency(gtransaction.amount)%></h5>
        </div>
        <hr>
        <p class="small text-secondary">Transaction by: <%= gtransaction.user.username.capitalize%></p>
      <hr>

      <div class="infocont d-flex justify-content-between">
      <p class="text-secondary small"><%= gtransaction.created_at.strftime("%b %d, %Y") %></p>
        <div class="btns">
          <%= link_to '<i class="fas fa-edit mr-3"></i>'.html_safe, edit_transaction_path(gtransaction), class:"text-dark"%></td>
          <%= link_to '<i class="fas fa-trash"></i>'.html_safe, gtransaction, method: :delete, data: { confirm: 'Are you sure?'}, class:"text-dark" %>
        </div>
      </div>
    </div>
  </div>

<% end %>
</div>

<%= link_to ' <i class="fas fa-arrow-left"></i> Back'.html_safe, groups_path,class:"text-white bg-dark px-2 py-1" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CapstoneTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<div class="container mt-md-3">
    <nav class="navbar navbar-expand-lg navbar-light bg-primary>
      <%= link_to "<i class='fas fa-wallet text-white mr-2'></i><span class='text-white'> Transaction Tracker</span>".html_safe, root_path, class: 'text-white' %>

      <div class="text-center mt-2 ml-auto">
        <%= showbtns %>
      </div>

  </nav>
</div>

<div class="container p-3 text-white">
  <%= yield %>
</div>
  </body>
</html>

app/views/transactions/_form.html.erb
<%= simple_form_for(@transaction) do |f| %>

<% if transaction.errors.any? %>
  <div id="error_explanation" class="bg-danger py-2 px-2 my-2">
    <h4><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h4>
    <ul>
      <% transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
    <div class="field mb-3">
      <%= f.label :title %>
      <%= f.text_field :title, class:"w-100", placeholder:"Title" %>
    </div>

    <div class="field mb-3">
      <%= f.label :amount %>
      <%= f.number_field :amount, class:"w-100", placeholder:"Amount" %>
    </div>

    <div class="field mb-3">
      <%= f.collection_select :group_id, Group.where(user_id: current_user),:id ,:title,{prompt:'select group'}, { class: "btn btn-light w-100" } %>
    </div>

    <div class="actions">
      <%= f.submit "Submit",class:"btn btn-warning btn-block rounded-0 py-2 mb-3" %>
    </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>
<%= link_to ' <i class="fas fa-arrow-left"></i> Back'.html_safe, transactions_path, class:"text-white bg-dark px-2 py-1" %>

app/views/transactions/etransaction.html.erb
<p id="notice"><%= notice %></p>


<h4 class="text-center">External Transactions</h4>


<div class="tamount text-dark text-center w-100 bg-warning py-2 border-bottom border-secondary">Total Amount: <%=number_to_currency(@etransaction_sum)%></div>
<div class="container2 px-0 py-2 px-1 overflow-auto">

    <% @etransactions.each do |etransaction| %>


    <div class="card mb-1">
      <div class="card-body text-primary">
        <div class="d-flex justify-content-between">
          <h5><%= etransaction.title.capitalize%></h5>
          <h5><%= number_to_currency(etransaction.amount)%></h5>
          </div>
          <hr>

          <div class="infocont d-flex justify-content-between">
              <p class="text-secondary small"><%= etransaction.created_at.strftime("%b %d, %Y") %></p>
              <div class="btns">
            <%= link_to '<i class="fas fa-edit mr-3"></i>'.html_safe, edit_transaction_path(etransaction), class:"text-dark"%></td>
            <%= link_to '<i class="fas fa-trash"></i>'.html_safe, etransaction, method: :delete, data: { confirm: 'Are you sure?'}, class:"text-dark" %>
            </div>
      </div>

      </div>
    </div>
    <% end %>

<br>
</div>

<%= link_to 'New Transaction', new_transaction_path, class:"bg-success text-white w-100 d-block mt-4 text-center py-2 mb-3" %>

<%=link_to ' <i class="fas fa-home"></i> Home'.html_safe, user_path(current_user), class:"mr-3 bg-dark text-white text-center px-2 py-1 radius w-100"%>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>


<h4 class="text-center">Grouped Transactions</h4>


<div class="tamount text-dark text-center w-100 bg-warning py-2 border-bottom border-secondary">Total Amount: <%=number_to_currency(@transaction_sum)%></div>
<div class="container2 px-0 py-2 px-1 overflow-auto">

    <% @transactions.each do |transaction| %>


    <div class="card mb-1">
      <div class="card-body text-primary">
        <div class="d-flex justify-content-between">
          <h5><%= transaction.title.capitalize%></h5>
          <h5><%= number_to_currency(transaction.amount)%></h5>
          </div>
          <hr>
          <div class="d-flex align-items-center">
          <img src="<%=transaction.group.icon%>" class="size mr-3 rounded-circle"/>
           <h5><%= transaction.group.title.capitalize%></h5>
          </div>
          <hr>
        <div class="infocont d-flex justify-content-between">
        <p class="text-secondary small"><%= transaction.created_at.strftime("%b %d, %Y") %></p>
          <div class="btns">
            <%= link_to '<i class="fas fa-edit mr-3"></i>'.html_safe, edit_transaction_path(transaction), class:"text-dark"%></td>
            <%= link_to '<i class="fas fa-trash"></i>'.html_safe, transaction, method: :delete, data: { confirm: 'Are you sure?'}, class:"text-dark" %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
<br>
</div>

<%= link_to 'New Transaction', new_transaction_path, class:"bg-success text-white w-100 d-block mt-4 text-center py-2 mb-3" %>

<%=link_to ' <i class="fas fa-home"></i> Home'.html_safe, user_path(current_user), class:"mr-3 bg-dark text-white text-center px-2 py-1 radius w-100"%>

app/views/transactions/new.html.erb
<h4 class="text-center mt-2">New Transaction</h4>

<%= render 'form', transaction: @transaction %>

<%= link_to "Create group", new_group_path, class:"text-white bg-success px-2 py-1" %>

<%= link_to ' <i class="fas fa-arrow-left"></i> Back'.html_safe, transactions_path, class:"text-white bg-dark px-2 py-1" %>

app/views/user/show.html.erb
<div class="container3 py-2 text-dark text-center">

<%= image_tag("demo.png", width: 80,class:"mt-3")%>

<h4 class="text-center w-title">Welcome back! <%= current_user.username %></h4>

<p class="w-75 msg">You can search for your transactions by clicking the buttons below:</p>


<div class="btns text-center">
<%= link_to '<i class="fas fa-credit-card fa-1x mr-2"></i>All my Transaction'.html_safe ,  transactions_path, class:"bg-dark text-white px-2 py-2 d-block w-50 mx-auto mb-2 rounded" %>
<%= link_to '<i class="fas fa-box-open mr-2 fa-1x"></i> All External Transaction'.html_safe ,  etransactions_path, class:"bg-dark text-white px-2 py-2 d-block w-50 mx-auto mb-2 rounded"  %>
<%= link_to '<i class="fas fa-layer-group mr-2 fa-1x"></i>All Groups'.html_safe ,  groups_path,class:"bg-dark text-white px-2 py-2 d-block w-50 mx-auto mb-2 rounded" %>
<%= link_to '+ Create New Transaction', new_transaction_path, class:"btn-success m-btn text-white w-50 m-auto d-block text-center py-2 mb-3" %>
</div>
</div>